### PR TITLE
Remove travel grant form

### PR DESCRIPTION
**Pull request by BenJam**
* remove notice on index.html
* keep travel support page (cool urls don’t change) but update text

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thank you, @BenJam.

**Comment by jdorfman** [comment]
We should have just removed travel grant form

**Comment by BenJam** [comment]
Oh dear. This may have been my hasty PR. Fails.

**Comment by RichardLitt** [comment]
@BenJam It was my bad. Should have waited to merge.

**Comment by jdorfman** [comment]
@BenJam @RichardLitt all good

**Pull request merged**
