### PR TITLE
Change Buy Tickets link

### PR DESCRIPTION
**Pull request by whit537**
Per (private) weekly call. @adamstac points out this is a bit easier of an entrypoint for people coming from the website to Open Collective.

Who's got the merge? @piamancini?

### CODE REVIEW

**Comment by piamancini** [comment]
Chad, can you modify to use this one? https://opencollective.com/sustainoss/events/2017

**Comment by jdorfman** [comment]
@whit537 @piamancini on it

**Comment by jdorfman** [comment]
@whit537 sorry about that!

**Comment by whit537** [comment]
No worries. :)

**Pull request closed without merging**
