### PR TITLE
Add previous Sustain Africa events

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
This PR:

- Adds the missing Sustain Africa events (2022 and 2023), including a customized logo and link to the report.
- Updates the link on the 2020 event to the right one.

I will create a separate PR to add the report for 2023 once it is published. Please let me know if I should adjust anything; thank you.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Great work, thank you! 

You could also submit a blogpost about the 2022 report, if you liked. :) Not too late to go out.

**Comment by BolajiAyodeji** [comment]
> Great work, thank you!
> 
> You could also submit a blogpost about the 2022 report, if you liked. :) Not too late to go out.

Thanks, @RichardLitt. Would this blog post be a short summary linking to the main report? Please let me know; thank you.

**Comment by RichardLitt** [comment]
Yep. Just throw it in the _posts folder in the repo. Let me know if you run into any hitches!

**Comment by BolajiAyodeji** [comment]
> Yep. Just throw it in the _posts folder in the repo. Let me know if you run into any hitches!

Alright. I'd find some time to do this before EOD tomorrow. Sure, I'll let you know. Thank you!

**Comment by RichardLitt** [comment]
There's no rush!

**Pull request merged**
