### PR TITLE
Add discourse link

### PR DESCRIPTION
**Pull request by ChrisChinchilla**

### CODE REVIEW

**Comment by jdorfman** [comment]
Restarting the deploy @ChrisChinchilla

**Comment by jdorfman** [comment]
@XhmikosR what does `test Expected — Waiting for status to be reported` mean?

**Comment by XhmikosR** [comment]
It means tests didn't fire up and it's a requirement for them to pass.

**Comment by RichardLitt** [comment]
Thanks, @ChrisChinchilla!

**Pull request merged**
