### PR TITLE
chore: update gems

### PR DESCRIPTION
**Pull request by RichardLitt**
Just updating them all. Not sure why this didn't change the Gemfile, but whatever?

### CODE REVIEW

**Comment by RichardLitt** [comment]
@XhmikosR Does this look right to you?

**Comment by XhmikosR** [comment]
I'm on mobile but CI seems to be broken.

We might need to update CI actions before this

**Comment by RichardLitt** [comment]
I think it is - still using old Node and older Ruby versions, and I'm not sure why. I would appreciate help!

**Comment by XhmikosR** [comment]
I'll have a look tomorrow!

**Comment by RichardLitt** [comment]
Thank you! No rush at all. I appreciate your work.

**Comment by XhmikosR** [comment]
@RichardLitt everything should be OK now. That .ruby-version file takes precedence over the Netlify dashboard environment variables so I had to update that too.

I only kept html-proofer back and eslint because they need more work and I don't have time. Generally, if CI is not green, the patch shouldn't land :)

**Comment by RichardLitt** [comment]
I wish I could look over your shoulder and see how you did this. There're some steps in here I don't fully understand. But again - grateful.

**Comment by XhmikosR** [comment]
I kept the patches separate for this reason :)

First CI, then gems, then npm deps and adapted the code if needed so that CI is still green.

**Pull request closed without merging**
