### PR TITLE
Rework About > Who

### PR DESCRIPTION
**Pull request by whit537**
- Bulletize ideal attendee profile
- Expand info on Gunner (closing #30)

### CODE REVIEW

**Comment by whit537** [comment]
Does this look okay for #30, @alnermcgunn?

**Comment by jdorfman** [comment]
LGTM want me to merge it or wait?

**Comment by whit537** [comment]
I think @alnermcgunn is on the call in a few minutes, I guess let's run it by him on the call if he's there and if not merge anyway.

**Comment by whit537** [comment]
@piamancini is talking to @alnermcgunn tomorrow, merging for now.

**Pull request merged**
