### PR TITLE
Add Sustainer Manifesto

### LINKED ISSUE #208: The Sustainers Manifesto
Todo:
- [x] Create Manifesto page
  - [x] [Get feedback](https://docs.google.com/document/d/1OiW7jS6TVhpLeuzDlGKZlyvQ5dD_5DfThIBPmAER_LI/edit#)
  - [x] Convert to markdown

### PR DESCRIPTION
**Pull request by jdorfman**
2-year-old issue now closed. Fixes #208

### CODE REVIEW

**Comment by RichardLitt** [comment]
I don't think this should have been merged, from a content perspective. 

@jdorfman, this is an interesting manifesto, but it doesn't have buy-in from everyone at Sustain. I also disagree with parts of it (the Licensing), and I don't recall pledging to support the the Manifesto.

There has to be another avenue for talking about this besides a PR to the website.

**Comment by XhmikosR** [comment]
Reverted it but kept the branch for future work.

**Comment by RichardLitt** [comment]
Thanks, @XhmikosR.

Justin: What is the purpose of this manifesto? Why was it only written by two people? Does this help us have more, better, and deeper conversations around what open source is, and how to sustain it in the long haul?

**Comment by jdorfman** [comment]
> @jdorfman, this is an interesting manifesto, but it doesn't have buy-in from everyone at Sustain. I also disagree with parts of it (like the Licensing section), and I don't recall pledging to support the Manifesto. There has to be another avenue for talking about this besides a PR to the website.

At the next meeting, we should talk about it.

> What is the purpose of this manifesto? 

More context to the definition.

> Why was it only written by two people? 

It was an [open discussion](https://discourse.sustainoss.org/t/sustainers-manifesto/39) in the forum. The only way things get done is by me making Pull Request. Annoying, sure for some, but what pisses me off is when nothing gets done. If I'm lucky I have _30 years left_, I don't want to look back and go "should have tried harder".  I'm not trying to be overdramatic, males who have my disorder on average live to 65. 

> Does this help us have more, better, and deeper conversations around what open source is, and how to sustain it in the long haul?

I strongly believe it does. With that said we should definitely have more eyeballs in it. Either way, I believe we should have one.

I should have made a better effort to promote this while @GeorgLink and I were working on it, that is where I failed, I admit that. For that, I apologize! Going forward I will make an effort to not just crowbar commits in.  =)

I hope there are no hard feelings and I appreciate you keeping me and everyone in check. This is not a dictatorship or BDFL situation, **_I just want progress_**. Help me. 🙏

**Comment by RichardLitt** [comment]
Thank you for explaining, Justin. I hear you when you say that you want to effect change, and you want to do it now. I, also, want to do that. I also hear you on not wanting to waste our finite time here, and to maximize our impact. I am only disagreeing with the how, not the why. 

Right now, there isn't a way to easily get a lot of buy-in from people in the Sustain community for a document like this. The way we're set up, the main conversations happen during the Sustain conference, in small groups. This means that some efforts, like adopting a manifesto, are very difficult, because they should encapsulate the community's thoughts as a whole, which is hard to gauge. Working Groups can produce reports, but something like a manifesto makes it sound like it comes from everyone, which is different. Unfortunately, the forum does not have a high amount of traffic. Neither do PRs to this website. So, neither of these places are good venues for moving manifesto-like documents forward. That doesn't mean it's impossible, it just means that I don't think it's the right place for them. I may simply be knee-jerk reacting, here, as I disagree with points in the manifesto, and as I think that manifestos in general aren't useful unless everyone buys in. 

On a related note, I also disagree weakly with the definition, and I would like to talk about it at some point. 

Let's talk about it at the next meeting: or, we can chat about it before hand, too, if you like. One idea for getting more eyes on this is to have a podcast around it. Another idea would be to send out a draft in the Newsletter and ask people for their thoughts. However, right now may not be a good time to ask for lots of volunteer effort, due to the strain of the WGs and COVID.

**Comment by GeorgLink** [comment]
Thanks @RichardLitt for the feedback on the manifesto and suggestions for process.
@jdorfman and I put this draft together precisely so that you could disagree with it and we can start the conversation of what should be in the manifesto. I didn't expect that our first pass would get accepted without changes and I look forward to having an open dialogue about the content of the manifesto. Unfortunately, I don't know what the best process for this would be either. I wouldn't mind having it as a clearly marked DRAFT somewhere prominent (website?) with a pointer to where feedback can be provided and the discussion can occur (forum?) and then reaching out to the people we want buying from individually (email) or inviting broad feedback (podcast & twitter).

**Comment by jdorfman** [comment]
@RichardLitt sounds good!

+1 @GeorgLink

**Pull request merged**
