### PR TITLE
Added sponsor types

### PR DESCRIPTION
**Pull request by jdorfman**
For Google and Tidelift

### CODE REVIEW

**Comment by jdorfman** [comment]
@XhmikosR help

**Comment by XhmikosR** [comment]
For starters don't use i when you want to use em.

Secondly make sure the & is escaped  as amp.

But I don't see the gain of this change. Is something else missing?

**Comment by XhmikosR** [comment]
Let me fix this later or tomorrow.

**Comment by XhmikosR** [comment]
@jdorfman What exactly are you trying to achieve here? Why do you use `blockquote` when it's clearly not a blockquote?

**Comment by jdorfman** [comment]
@XhmikosR I need to identify what type of sponsorship certain companies chose. I would like it in italic centered under the logo.

**Comment by XhmikosR** [comment]
OK, I will try to fix it later and ping you.

**Comment by jdorfman** [comment]
Sounds good. We also need the sponsor types to line up. I know I can do it by exporting the logos/svgs with the identical padding which I have no issue doing. If there is another way you prefer LMK.

image

**Pull request merged**
