### PR TITLE
Changed logo and main hero image

### PR DESCRIPTION
**Pull request by AnXh3L0**
Another PR that also includes new favicons.

### CODE REVIEW

**Comment by jdorfman** [comment]
awesome thanks @AnXh3L0 

@XhmikosR and I will take a look asap

**Comment by XhmikosR** [comment]
Never, ever, commit unoptimized images. This isn't magazines, this is a website.

Also, do not make the favicons yourself.

**Comment by XhmikosR** [comment]
Where is the new SVG images that should be used for the favicons?

**Comment by XhmikosR** [comment]
Nvm, found it.

**Comment by elioqoshi** [comment]
@XhmikosR I think your tone is inappropriate considering someone is helping in their spare time.

**Comment by XhmikosR** [comment]
Right, everyone else is being paid.

My tone is like that because I keep seeing the same mistakes.

**Pull request merged**
