### PR TITLE
Adding note on rough consensus

### PR DESCRIPTION
**Pull request by RichardLitt**
Also adding my own email.

<a href="https://gitpod.io/#https://github.com/sustainers/website/pull/328"></a>

### CODE REVIEW

**Comment by RichardLitt** [comment]
Not sure why the build failed. thoughts, @XhmikosR or @jdorfman?

**Comment by XhmikosR** [comment]
Someone seems to have messed with the Gems...

**Comment by XhmikosR** [comment]
Or it's something with Actions. I suggest that you restart the workflows a little later :)

**Comment by RichardLitt** [comment]
K. Will try again in a few hours. Thanks!

**Comment by XhmikosR** [comment]
@RichardLitt Should be good to go now. I updated the gems and everything seems good now.

**Review by XhmikosR — APPROVED** [review]

**Comment by RichardLitt** [comment]
Ta!

**Comment by jdorfman** [comment]
Thanks @XhmikosR 

Miss ya =)

**Pull request merged**
