### PR TITLE
Drop dollar sign from logo

### LINKED ISSUE #93: Drop dollar sign from $ustain
Per @alnermcgunn on private weekly call.

- U.S.-centric
- too much emphasis on cash, sustainability is more than money

In favor of SustainOSS.

### PR DESCRIPTION
**Pull request by XhmikosR**
@jdorfman: I'll push here when I'm done and merge.

Fixes #93

### CODE REVIEW

**Comment by jdorfman** [comment]
Cool. Try to get the <title> too

**Comment by XhmikosR** [comment]
Yeah, I already changed every instance.

**Comment by jdorfman** [comment]
Heart

**Comment by XhmikosR** [comment]
@jdorfman: can you upload, not commit, the sustain-small.svg with background color of `#263238`?

I need to fix the small favicons and then I'll merge.

**Comment by jdorfman** [comment]
@XhmikosR for sure

**Comment by jdorfman** [comment]
@XhmikosR https://cl.ly/2S3M1C2g1G26

**Pull request merged**
