### PR TITLE
Notes/Summary of the Personas working session at Sustain 2020

### PR DESCRIPTION
**Pull request by jredding**
Adding the notes and a summary of the personas working session at Sustain 2020.

### CODE REVIEW

**Comment by jredding** [comment]
These commits should be squashed. If this is done during merge then yay! but if not I'll cancel this PR then rebase and resubmit a new P.R.  No sense in having my "save, another save, further save" commit history into the long-term history of the website ;).

**Comment by jdorfman** [comment]
Thanks @jredding. @RichardLitt will take a look asap. :)

**Comment by RichardLitt** [comment]
Love these notes. Thanks, Jacob!

**Comment by RichardLitt** [comment]
@jredding How can people contact you? Should we add an email?

**Comment by jdorfman** [comment]
Added to our Forum: https://discourse.sustainoss.org/t/personas-on-sustainability/421

**Comment by jredding** [comment]
sure.. I'll add an email and I'll also update a few of the spelling errors, like the BenJam highlighted ;).

**Pull request merged**
