### PR TITLE
authentic-participation: Fill out template

### PR DESCRIPTION
**Pull request by jwflory**
@jdorfman pointed this out to me, so here is my first pass on filling
out the template on the Principles of Authentic Participation. I include
some helpful calls-to-action for folks who want to learn more or get
involved with what we have going so far.

Related to #238.

### CODE REVIEW

**Comment by jdorfman** [comment]
@jwflory looks great. I'm not concerned with design right now, content is king.

Let's link

Image 2020-03-26 at 1 54 05 PM

to 

`/working-groups/authentic-participation/`

and I'll merge it.

Bonus points if you change "WORKING GROUPS" from green to white

Image 2020-03-26 at 1 55 11 PM

**Comment by jwflory** [comment]
Hey @jdorfman! I'm going to need to figure out this one out. Since the working groups page is built from `_data/wgs.yml`, it isn't possible for me to use Markdown syntax to link. There would be an easy fix but I think it would make _all_ of the working group titles link out to the same working group. It will probably take some changing around with the YAML structure and styling to get that to link. I'm guessing! I haven't worked with this site's codebase before, so I haven't gone very deep here.

**Comment by RichardLitt** [comment]
I had another idea for implementing a link: namely, adding a button. I know what I was planning to do when the first person had their page ready, I just haven't had time. The site is a bit confusing at the moment due to restrictions in Jekyll, and I haven't documented it because it's still live. Give me a minute - this isn't @jwflory's job to do. :) 

On the other side of things: @jwfory, awesome work getting this filled out before I contacted you. I have on my list of things to do to contact everyone. This wasn't an oversight, I just have a lot on my plate, and I was going to get to you today or tomorrow. 

Thanks for changing "Rationale" to "Purpose" - I like that wording much more. 

Give me a bit to do these changes.

**Comment by RichardLitt** [comment]
Thank you, @jwflory and @jdorfman! Let me know what you think. I've added a button to the main page.

**Comment by jdorfman** [comment]
@jwflory @RichardLitt I love this momentum. Let's keep it going.

I'll ask @XhmikosR for some UX advice, he is really good at it.

**Comment by XhmikosR** [comment]
>I'll ask @XhmikosR for some UX advice, he is really good at it.

Nah, quite the opposite 😛

**Comment by jwflory** [comment]
> On the other side of things: @jwfory, awesome work getting this filled out before I contacted you. I have on my list of things to do to contact everyone. This wasn't an oversight, I just have a lot on my plate, and I was going to get to you today or tomorrow.

All good. @jdorfman pointed it out to me in an email, so I figured to just go for it. :slightly_smiling_face: No reflection on your part!

Thanks for working on this and getting it published. I appreciate your time on this @RichardLitt.

**Comment by jdorfman** [comment]
@jwflory he is being modest.

**Pull request merged**
