### PR TITLE
Adding a tinyletter subscribe form

### PR DESCRIPTION
**Pull request by RichardLitt**
See #37

### CODE REVIEW

**Comment by RichardLitt** [comment]
Ping @jdorfman

**Comment by jdorfman** [comment]
@RichardLitt can you attach a screenshot? I can't open a terminal ATM

**Comment by RichardLitt** [comment]
screen shot 2017-04-06 at 2 35 39 pm

**Comment by jdorfman** [comment]
Don't merge yet.

**Comment by RichardLitt** [comment]
Aight. What can I change?

**Comment by jdorfman** [comment]
@RichardLitt I am just testing it locally. Can you share the tinyletter credentials on slack so I can check my QA?

**Comment by jdorfman** [comment]
I think we need form validation before the form submission. See: https://cl.ly/3o0j0n3m341D

**Comment by jdorfman** [comment]
Great job @RichardLitt !

**Pull request merged**
