### PR TITLE
Changed Events page by adding the 2019 logo

### PR DESCRIPTION
**Pull request by AnXh3L0**

### CODE REVIEW

**Comment by jdorfman** [comment]
@XhmikosR please advise

**Comment by XhmikosR** [comment]
I will pull this to a branch tomorrow, thanks.

**Comment by AnXh3L0** [comment]
Any update on this?

**Comment by jdorfman** [comment]
@AnXh3L0 waiting for @XhmikosR, he is swamped with other projects

**Comment by XhmikosR** [comment]
I'm gonna close this since this can't be merged anyway, and I will pick up any things I need later. Generally I personally need just the assets and the mockups (pictures).

**Pull request closed without merging**
