### PR TITLE
Add jekyll-feed gem to enable atom feed

### PR DESCRIPTION
**Pull request by andrew**
This adds the ['jekyll-feed'](https://github.com/jekyll/jekyll-feed) gem to the Gemfile and its corresponding dependency in the Gemfile.lock and _config.yml files.

The atom feed is then available at /feed.xml

Also of note, the website currently needs ruby 3.1 to build, I may open a seperate pull request to update the version to 3.3.0.

### CODE REVIEW

**Comment by andrew** [comment]
We'll also need to add links to the rss feed in the layout of the website

**Comment by RichardLitt** [comment]
Does this work for the stuff in _posts? 

Should we have a button or icon that makes this available for people to use on the website, also in this PR?

**Comment by andrew** [comment]
Opened a seperate PR to declare the specific version of ruby currently required: https://github.com/sustainers/website/pull/373

**Comment by andrew** [comment]
> Does this work for the stuff in _posts?

Yep, by default for the 10 latest posts in `_posts`

> Should we have a button or icon that makes this available for people to use on the website, also in this PR?

I can add something here, or do it in a seperate PR

**Comment by andrew** [comment]
@RichardLitt I've added the auto-discovery metatag to the head of the layout, any suggestions on where on the page to add the icon? Also I see there are some svg icons in the repo already, any idea where they came from?

**Comment by RichardLitt** [comment]
In the footer next to the GitHub icon would be great! Alternatively, a new line in the Blog template at the bottom that says "sign up here for Blog RSS updates". What do you think? 

No idea where those .svgs are from.

**Comment by andrew** [comment]
I did a reverse image search on the existing icons and they look to me like the bootstrap icons, so I used this one for rss: https://icons.getbootstrap.com/icons/rss-fill/

Screenshot 2024-01-16 at 14 46 47

**Review by RichardLitt — APPROVED** [review]

**Comment by RichardLitt** [comment]
Looks great! Thank you, @andrew. :)

**Comment by andrew** [comment]
Nice! I validated the feed and it looks like one of the posts is missing some metadata, but otherwise good: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsustainoss.org%2Ffeed.xml

**Comment by RichardLitt** [comment]
I've added Author fields to all of the posts. :)

**Pull request merged**
