### PR TITLE
Add Governance Readiness WG webpage

### PR DESCRIPTION
**Pull request by jlcanovas**
This PR adds the contents for the Governance Readiness WG page.

### CODE REVIEW

**Comment by jdorfman** [comment]
Thanks @jlcanovas! @RichardLitt will check this out asap =)

**Comment by XhmikosR** [comment]
@jlcanovas time to enable https on your site 😛

**Comment by XhmikosR** [comment]
About ignoring html-proofer links/content/etc: https://github.com/gjtorikian/html-proofer#ignoring-content

Alternatively, we could disable the https link check, although no content should be served via plain http IMHO.

**Comment by jdorfman** [comment]
Thanks @jlcanovas & @XhmikosR for the test fix

https://discourse.sustainoss.org/c/working-groups/17

**Comment by jlcanovas** [comment]
Thanks! 

@XhmikosR you are so right, I should update my site to https 😃

**Comment by XhmikosR** [comment]
@jlcanovas if you do, don't forget to submit a PR to update the links and re-add the html-proofer check 🙂

**Comment by jlcanovas** [comment]
count on that!

**Comment by RichardLitt** [comment]
Thanks, @jlcanovas! This looks great. :)

**Pull request merged**
