### PR TITLE
Update business-models.md

### PR DESCRIPTION
**Pull request by abiro**
Hi,

I've updated the group name and added a link to the forums to join the discussion.

Best,
Agost

### CODE REVIEW

**Comment by jdorfman** [comment]
Hey @abiro awesome, @RichardLitt will check this out asap =)

**Comment by RichardLitt** [comment]
Thanks, @abiro. Want me to remove the unused sections?

**Comment by abiro** [comment]
Thanks @RichardLitt, I expect to fill the unused sections later on. In the meantime I'm not sure if they should stay unfilled or be removed.

**Comment by RichardLitt** [comment]
I think, at a minimum, I want to have one questions answer: why does this working group exist? What are we trying to solve with it? 

Do you want help answering this for this WG? I'm happy to take a stab at writing it.

**Comment by abiro** [comment]
Ok, I had an other look and I think I get what’s needed. Will submit a
better version this week. :)

**Comment by RichardLitt** [comment]
@abiro Thank you! No pressure. If this is too much, let me know, and I can draft something up. :)

**Comment by RichardLitt** [comment]
@abiro Ping. :)

**Comment by RichardLitt** [comment]
Merged. I filled out some of the data; want to check it, at some point? No rush.

**Comment by abiro** [comment]
Thanks @RichardLitt and apologies for not responding sooner. I'm not sure how to proceed with the working group, as it seems that I'm the only one interested in contributing to the project so far. I've started working on a draft on my own and figured that I'd pick up the working group and try to involve others again once I've produced some material.

**Comment by RichardLitt** [comment]
I think that's alright. We've done what we can, at this point: there's a public link describing it, a conversation on the forums, and your own efforts. If someone shows up, that's great. If not, it happens. :)

Once you have a draft, emailing others (the attendees in the group, individuals you talked to about this on the day) and asking for feedback is probably a good way to get engagement. I would suggest that.

**Pull request merged**
