### PR TITLE
Make website

### PR DESCRIPTION
**Pull request by whit537**
Aiming for GitHub Pages.

2b150d3a-d8e9-11e6-86e2-f928f12d4d29

### Todo

- [x] svgs for art
- [x] font
- [ ] where does "Buy Tickets" go?
- [ ] where does "19 remaining" come from? (nice-to-have)
- [x] write copy
  - [x] agenda
  - [x] about
  - [x] sponsor
  - [x] code of conduct
  - [x] diversity
- [x] svg logos for sponsor orgs

### CODE REVIEW

**Comment by jdorfman** [comment]
@whit537 agenda: https://github.com/sustainers/website/blob/jd-write-copy/agenda.md

**Comment by jdorfman** [comment]
Link to assets: https://www.dropbox.com/s/mv069pig10ygkbg/Folder_Sustain_Project.zip?dl=0

**Comment by whit537** [comment]
screen shot 2017-01-14 at 7 31 52 am

**Comment by whit537** [comment]
screen shot 2017-01-14 at 7 44 10 am

**Comment by whit537** [comment]
screen shot 2017-01-14 at 7 57 54 am

**Comment by whit537** [comment]
Blech! Those SVGs are actually just JPEGs wrapped in SVGs. 😮

**Comment by jdorfman** [comment]
@whit537 would this work?: https://cl.ly/161e241N451y

If so I will export the rest

**Comment by whit537** [comment]
Actually, scratch that. There are paths in there, there's just tons of other crap, too. Opening in Sketch and exporting back to SVG cuts file size by 99%. 👍

**Comment by whit537** [comment]
lol ... great minds, @jdorfman. ;-)

Yeah, that's perfect. Export the rest! 🚢

**Comment by jdorfman** [comment]
Exported and optimized with Jake's amazing tool. Check slack

**Comment by whit537** [comment]
Rebased with new SVGs. Previous head was 17c45e1a32412f23b2a549f5d976c614fe37d0f3.

**Comment by whit537** [comment]
13695e940788f692279bf1966107277605c99ddb

screen shot 2017-01-17 at 8 31 07 am

**Comment by whit537** [comment]
I'm not sure if that's the best way to do the font sizes; will revisit.

**Comment by whit537** [comment]
First pass on homepage done in 94ac94943c332ac5c702809c2df76de0c92928aa.

screen shot 2017-01-17 at 9 24 34 am
 
screen shot 2017-01-17 at 9 24 37 am

**Comment by whit537** [comment]
Kinda oversized on wider screens tho.

6ujabeasaj

**Comment by jdorfman** [comment]
Nice! Can we put it on a temp staging server to share with the others?

**Pull request merged**
